local_pem_path = r'C:\\Users\yaniv\Documents\get-a-job\USeast1keypair.pem'
remote_pem_path = '/home/ec2-user/USeast1keypair.pem'
user = 'ec2-user'
search_term = 'Main'
bash_script_path = '/home/ec2-user/git/get_ips.sh'
ip_text_path = '/home/ec2-user/worker_ips.txt'